# Generated by Django 4.2.13 on 2024-06-23 11:56

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0013_heartreaction'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HeartReaction',
            new_name='Like',
        ),
        migrations.AlterUniqueTogether(
            name='like',
            unique_together=set(),
        ),
    ]
