# Generated by Django 4.2.13 on 2024-06-24 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
